version: 2.1
orbs:
  snyk: snyk/snyk@1.1.2
jobs:
  build:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: false
          project: '${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH}-app'
          severity-threshold: low
          token-variable: SNYK_TOKEN
workflows: null
